<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADS29" ignored="0" name="Test" tests="34" failures="26" timestamp="17 Jul 2017 05:51:19 GMT" time="5.898" errors="0">
  <testcase name="HS_DBConnCheck_TC001" time="0.799" classname="exe.HS_TS001_ConnCheck"/>
  <testcase name="HS_InputFileExistance_TC002" time="0.308" classname="exe.HS_TS001_ConnCheck"/>
  <testcase name="HS_FileLevelRecCount_TC003" time="0.085" classname="exe.HS_TS002_RecCount">
    <failure type="junit.framework.AssertionFailedError" message="Row count Check Fail expected:&amp;lt;115&amp;gt; but was:&amp;lt;111&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Row count Check Fail expected:<115> but was:<111>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS002_RecCount.HS_FileLevelRecCount_TC003(HS_TS002_RecCount.java:68)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_FileLevelRecCount_TC003 -->
  <testcase name="HS_Record_Type_AS_Debt_Cancel_TC004" time="0.065" classname="exe.HS_TS003_Record_Type_DataValidation"/>
  <testcase name="HS_Record_Type_AS_Debt_Delinquent_Letter_TC005" time="0.043" classname="exe.HS_TS003_Record_Type_DataValidation"/>
  <testcase name="HS_Record_Type_AS_HS_DownGrade_TC006" time="0.059" classname="exe.HS_TS003_Record_Type_DataValidation">
    <failure type="junit.framework.AssertionFailedError" message="HS_DownGrade counts are Not Equal expected:&amp;lt;14&amp;gt; but was:&amp;lt;13&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: HS_DownGrade counts are Not Equal expected:<14> but was:<13>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS003_Record_Type_DataValidation.HS_Record_Type_AS_HS_DownGrade_TC006(HS_TS003_Record_Type_DataValidation.java:141)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Record_Type_AS_HS_DownGrade_TC006 -->
  <testcase name="HS_Record_Type_AS_HS_Price_Increase_TC007" time="0.045" classname="exe.HS_TS003_Record_Type_DataValidation"/>
  <testcase name="HS_Record_Type_AS_NULL_TC008" time="0.046" classname="exe.HS_TS003_Record_Type_DataValidation"/>
  <testcase name="HS_Mailing_City_Mandatory_Check_TC010" time="0.01" classname="exe.HS_TS004_Mandatory_Column_Check">
    <failure type="junit.framework.AssertionFailedError" message="Mailing_City is not Null | Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Mailing_City is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS004_Mandatory_Column_Check.HS_Mailing_City_Mandatory_Check_TC010(HS_TS004_Mandatory_Column_Check.java:90)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Mailing_City_Mandatory_Check_TC010 -->
  <testcase name="HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011" time="0.011" classname="exe.HS_TS004_Mandatory_Column_Check">
    <failure type="junit.framework.AssertionFailedError" message="Partner_Account_Number is not Null or Length of Account number is not Correct expected:&amp;lt;0&amp;gt; but was:&amp;lt;21&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Partner_Account_Number is not Null or Length of Account number is not Correct expected:<0> but was:<21>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS004_Mandatory_Column_Check.HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011(HS_TS004_Mandatory_Column_Check.java:119)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011 -->
  <testcase name="HS_Premise_City_Mandatory_Check_TC008" time="0.009" classname="exe.HS_TS004_Mandatory_Column_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_City is not Null | Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_City is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS004_Mandatory_Column_Check.HS_Premise_City_Mandatory_Check_TC008(HS_TS004_Mandatory_Column_Check.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_City_Mandatory_Check_TC008 -->
  <testcase name="HS_Premise_State_Mandatory_Check_TC009" time="0.008" classname="exe.HS_TS004_Mandatory_Column_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_State is not Null | Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_State is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS004_Mandatory_Column_Check.HS_Premise_State_Mandatory_Check_TC009(HS_TS004_Mandatory_Column_Check.java:61)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_State_Mandatory_Check_TC009 -->
  <testcase name="HS_Contract_SchedRef_TC012" time="0.008" classname="exe.HS_TS005_Contract_SchedRef_Check">
    <failure type="junit.framework.AssertionFailedError" message="HS_Contract_SchedRef can not be Zero expected:&amp;lt;0&amp;gt; but was:&amp;lt;14&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: HS_Contract_SchedRef can not be Zero expected:<0> but was:<14>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS005_Contract_SchedRef_Check.HS_Contract_SchedRef_TC012(HS_TS005_Contract_SchedRef_Check.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Contract_SchedRef_TC012 -->
  <testcase name="HS_Contract_SchedRef_TC013" time="0.007" classname="exe.HS_TS005_Contract_SchedRef_Check">
    <failure type="junit.framework.AssertionFailedError" message="HS_Contract_SchedRef Is Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: HS_Contract_SchedRef Is Mandatory expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS005_Contract_SchedRef_Check.HS_Contract_SchedRef_TC013(HS_TS005_Contract_SchedRef_Check.java:61)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Contract_SchedRef_TC013 -->
  <testcase name="HS_Premise_Home_Phone_Check_TC013" time="0.007" classname="exe.HS_TS006_Phone_Number_Check"/>
  <testcase name="HS_Premise_Home_Phone_Check_TC014" time="0.006" classname="exe.HS_TS006_Phone_Number_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Home_Phone_Number length not less than 10 Digits expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Home_Phone_Number length not less than 10 Digits expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS006_Phone_Number_Check.HS_Premise_Home_Phone_Check_TC014(HS_TS006_Phone_Number_Check.java:61)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Home_Phone_Check_TC014 -->
  <testcase name="HS_Premise_Work_Phone_Check_TC015" time="0.006" classname="exe.HS_TS006_Phone_Number_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Work_Phone_Number length not less than 10 Digits expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS006_Phone_Number_Check.HS_Premise_Work_Phone_Check_TC015(HS_TS006_Phone_Number_Check.java:90)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Work_Phone_Check_TC015 -->
  <testcase name="HS_Premise_Work_Phone_Check_TC016" time="0.006" classname="exe.HS_TS006_Phone_Number_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Work_Phone_Number length not less than 10 Digits expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS006_Phone_Number_Check.HS_Premise_Work_Phone_Check_TC016(HS_TS006_Phone_Number_Check.java:119)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Work_Phone_Check_TC016 -->
  <testcase name="HS_Premise_Work_Phone_Check_TC017" time="0.005" classname="exe.HS_TS006_Phone_Number_Check"/>
  <testcase name="HS_Premise_First_Name_Check_TC018" time="0.007" classname="exe.HS_TS007_Premise_Name_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_First_Name is Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;14&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_First_Name is Mandatory expected:<0> but was:<14>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS007_Premise_Name_Check.HS_Premise_First_Name_Check_TC018(HS_TS007_Premise_Name_Check.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_First_Name_Check_TC018 -->
  <testcase name="HS_Premise_Last_Name_Check_TC019" time="0.016" classname="exe.HS_TS007_Premise_Name_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Last_Name is Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Last_Name is Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_TS007_Premise_Name_Check.HS_Premise_Last_Name_Check_TC019(HS_TS007_Premise_Name_Check.java:61)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Last_Name_Check_TC019 -->
  <testcase name="HS_AEPCustomer_FirstName_Check_TC020" time="0.034" classname="exe.HS_TS008_AEPCustomer_Details_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.aepcustomer&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.aepcustomer' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_FirstName_Check_TC020(HS_TS008_AEPCustomer_Details_Check.java:33)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_FirstName_Check_TC020 -->
  <testcase name="HS_AEPAudit_Date_Check_TC025" time="0.009" classname="exe.HS_TS009_AEPAudit_Details_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.aepaudit&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.aepaudit' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS009_AEPAudit_Details_Check.HS_AEPAudit_Date_Check_TC025(HS_TS009_AEPAudit_Details_Check.java:35)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPAudit_Date_Check_TC025 -->
  <testcase name="HS_SJPayments_AccountNumber_Check_TC028" time="0.009" classname="exe.HS_TS010_PaymentsFromPartner_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.sjpaymentsfrompartner&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.sjpaymentsfrompartner' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_AccountNumber_Check_TC028(HS_TS010_PaymentsFromPartner_Check.java:31)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_AccountNumber_Check_TC028 -->
  <testcase name="HS_SJPayments_ChargeType_Check_TC029" time="0.006" classname="exe.HS_TS010_PaymentsFromPartner_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.sjpaymentsfrompartner&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.sjpaymentsfrompartner' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_ChargeType_Check_TC029(HS_TS010_PaymentsFromPartner_Check.java:57)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_ChargeType_Check_TC029 -->
  <testcase name="HS_SJPayments_Invoice_Number_Check_TC030" time="0.007" classname="exe.HS_TS010_PaymentsFromPartner_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.sjpaymentsfrompartner&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.sjpaymentsfrompartner' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Invoice_Number_Check_TC030(HS_TS010_PaymentsFromPartner_Check.java:86)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Invoice_Number_Check_TC030 -->
  <testcase name="HS_SJPayments_Partner_ChargeSign_Check_TC032" time="0.006" classname="exe.HS_TS010_PaymentsFromPartner_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.sjpaymentsfrompartner&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.sjpaymentsfrompartner' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Partner_ChargeSign_Check_TC032(HS_TS010_PaymentsFromPartner_Check.java:143)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Partner_ChargeSign_Check_TC032 -->
  <testcase name="HS_SJPayments_Partner_Record_Type_Check_TC033" time="0.005" classname="exe.HS_TS010_PaymentsFromPartner_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.sjpaymentsfrompartner&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.sjpaymentsfrompartner' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Partner_Record_Type_Check_TC033(HS_TS010_PaymentsFromPartner_Check.java:172)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Partner_Record_Type_Check_TC033 -->
  <testcase name="HS_SJPayments_Transaction_Amount_Check_TC031" time="0.005" classname="exe.HS_TS010_PaymentsFromPartner_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.sjpaymentsfrompartner&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.sjpaymentsfrompartner' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Transaction_Amount_Check_TC031(HS_TS010_PaymentsFromPartner_Check.java:114)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Transaction_Amount_Check_TC031 -->
  <testcase name="HS_AEPCustomer_LastName_Check_TC021" time="0.007" classname="exe.HS_TS008_AEPCustomer_Details_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.aepcustomer&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.aepcustomer' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_LastName_Check_TC021(HS_TS008_AEPCustomer_Details_Check.java:72)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_LastName_Check_TC021 -->
  <testcase name="HS_AEPAudit_ProductCodes_Null_Check_TC026" time="4.089" classname="exe.HS_TS009_AEPAudit_Details_Check">
    <failure type="com.mysql.cj.jdbc.exceptions.CommunicationsException" message="Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.">
      <![CDATA[com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:590)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:57)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_TS009_AEPAudit_Details_Check.HS_AEPAudit_ProductCodes_Null_Check_TC026(HS_TS009_AEPAudit_Details_Check.java:60)
Caused by: com.mysql.cj.core.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:93)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:133)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:149)
	at com.mysql.cj.mysqla.io.MysqlaSocketConnection.connect(MysqlaSocketConnection.java:83)
	at com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1726)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)
	... 31 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.cj.core.io.StandardSocketFactory.connect(StandardSocketFactory.java:202)
	at com.mysql.cj.mysqla.io.MysqlaSocketConnection.connect(MysqlaSocketConnection.java:57)
	... 34 more
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPAudit_ProductCodes_Null_Check_TC026 -->
  <testcase name="HS_AEPCustomer_MailingAddressState_Check_TC022" time="0.016" classname="exe.HS_TS008_AEPCustomer_Details_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.aepcustomer&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.aepcustomer' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_MailingAddressState_Check_TC022(HS_TS008_AEPCustomer_Details_Check.java:119)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_MailingAddressState_Check_TC022 -->
  <testcase name="HS_AEPCustomer_PremisesAddressZipPlus4_Check_TC023" time="0.048" classname="exe.HS_TS008_AEPCustomer_Details_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.aepcustomer&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.aepcustomer' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_PremisesAddressZipPlus4_Check_TC023(HS_TS008_AEPCustomer_Details_Check.java:218)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_PremisesAddressZipPlus4_Check_TC023 -->
  <testcase name="HS_AEPCustomer_UniqueID_Check_TC024" time="0.011" classname="exe.HS_TS008_AEPCustomer_Details_Check">
    <failure type="java.sql.SQLSyntaxErrorException" message="Table &amp;apos;homeserve.aepcustomer&amp;apos; doesn&amp;apos;t exist">
      <![CDATA[java.sql.SQLSyntaxErrorException: Table 'homeserve.aepcustomer' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at exe.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_UniqueID_Check_TC024(HS_TS008_AEPCustomer_Details_Check.java:264)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_UniqueID_Check_TC024 -->
</testsuite> <!-- Test -->
